version: 2

jobs:
  node:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - run: npx jetify

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: "jest test"
          command: npm run test:coverage
          no_output_timeout: 20m

      - run:
          name: "Upload to codecov"
          command: bash <(curl -s https://codecov.io/bash) -cF javascript

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
